Repository ASFHyP3/hyp3-isce2, pull requests merged in 2023-07, with the labels that each got.

#100 Add `create-jira-issue.yml`
  .github/workflows/create-jira-issue.yml
Labels: bumpless

#106 Release v0.5.0
  .github/workflows/coverage-report.yml
  .github/workflows/create-jira-issue.yml
  CHANGELOG.md
  README.md
  images/coverage.svg
  src/hyp3_isce2/burst.py
  tests/test_burst.py
Labels: minor

#108 use native dem (30m) for the calculation, resample the product with p…
  CHANGELOG.md
  src/hyp3_isce2/dem.py
  src/hyp3_isce2/insar_tops_burst.py
  tests/test_dem.py
Labels: minor

#109 release v0.6.0
  CHANGELOG.md
  src/hyp3_isce2/dem.py
  src/hyp3_isce2/insar_tops_burst.py
  tests/test_dem.py
Labels: minor

#113 set tiling and compression options for water mask geotiff
  src/hyp3_isce2/water_mask.py
  tests/test_water_mask.py
Labels: bumpless

#114 fix reference to single browse image in insar_tops_burst readme
  src/hyp3_isce2/metadata/templates/insar_burst/readme.md.txt.j2
Labels: bumpless

#116 Proposed edits to process in readme PR
  README.md
  src/hyp3_isce2/metadata/templates/insar_burst/readme.md.txt.j2
Labels: bumpless

#115 Update process in readme.md.txt.j2 and repo README.md
  CHANGELOG.md
  README.md
  src/hyp3_isce2/metadata/templates/insar_burst/readme.md.txt.j2
Labels: patch

#117 update the readme.md.txt.j2 to include create_water_mask in the processing
  src/hyp3_isce2/metadata/templates/insar_burst/readme.md.txt.j2
Labels: bumpless

#118 Release v 0.6.1
  CHANGELOG.md
  README.md
  environment.yml
  images/coverage.svg
  src/hyp3_isce2/insar_tops_burst.py
  src/hyp3_isce2/metadata/templates/insar_burst/readme.md.txt.j2
  src/hyp3_isce2/water_mask.py
  tests/data/test_geotiff.tif
  tests/data/water_mask_input.tif
  tests/test_water_mask.py
Labels: patch
