Repository ASFHyP3/hyp3-isce2, pull requests merged in 2023-10, with the labels that each got.

#148 Update Documentation of the Water Mask Process
  src/hyp3_isce2/insar_tops_burst.py
  src/hyp3_isce2/metadata/templates/insar_burst/readme.md.txt.j2
Labels: bumpless, documentation

#150 Fixed Typo in Changelog
  CHANGELOG.md
Labels: bumpless

#149 Release 0.8.0
  .github/workflows/changelog.yml
  .github/workflows/create-jira-issue.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release-checklist-comment.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-version.yml
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  environment.yml
  images/coverage.svg
  src/hyp3_isce2/insar_tops_burst.py
  src/hyp3_isce2/metadata/templates/insar_burst/readme.md.txt.j2
  src/hyp3_isce2/utils.py
  src/hyp3_isce2/water_mask.py
  tests/test_utils.py
  tests/test_water_mask.py
Labels: minor

#152 Release v0.8.1
  CHANGELOG.md
  src/hyp3_isce2/utils.py
Labels: patch
