Repository ASFHyP3/hyp3-isce2, pull requests merged in 2023-04, with the labels that each got.

#6 Download DEM for burst bounding box
  environment.yml
  src/hyp3_isce2/dem.py
  tests/test_dem.py
Labels: bumpless

#8 Add ancillary data download functionality
  src/hyp3_isce2/burst.py
  src/hyp3_isce2/process.py
  src/hyp3_isce2/s1_auxcal.py
  tests/test_burst.py
  tests/test_s1_auxcal.py
Labels: bumpless

#9 Add template creation functionality
  environment.yml
  src/hyp3_isce2/process.py
  src/hyp3_isce2/templates/topsapp.xml
  src/hyp3_isce2/topsapp.py
  tests/test_topsapp.py
Labels: bumpless

#12 Add ability to run topsapp steps for bursts
  .github/workflows/test-and-build.yml
  environment.yml
  src/hyp3_isce2/burst.py
  src/hyp3_isce2/dem.py
  src/hyp3_isce2/process.py
  src/hyp3_isce2/s1_auxcal.py
  src/hyp3_isce2/templates/topsapp.xml
  src/hyp3_isce2/topsapp.py
  tests/test_topsapp.py
Labels: bumpless

#24 Remove unused import
  tests/test_topsapp.py
Labels: bumpless

#27 Fix release checklist typo
  .github/workflows/release-checklist-comment.yml
  CHANGELOG.md
Labels: bug, patch

#31 Add insar_stripmap entrypoint skeleton for AVO
  CHANGELOG.md
  pyproject.toml
  src/hyp3_isce2/__main__.py
  src/hyp3_isce2/insar_stripmap.py
  tests/test_entrypoints.py
Labels: patch

#32 Update Readme
  README.md
  images/arch_here.jpg
Labels: bumpless

#33 Upgrade to ISCE2 2.6.3
  .github/workflows/test-and-build.yml
  environment.yml
Labels: bumpless

#34 Release v0.2.0
  .github/workflows/release-checklist-comment.yml
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  README.md
  environment.yml
  images/arch_here.jpg
  pyproject.toml
  src/hyp3_isce2/__main__.py
  src/hyp3_isce2/burst.py
  src/hyp3_isce2/etc/download_example.py
  src/hyp3_isce2/insar_stripmap.py
  src/hyp3_isce2/insar_tops_burst.py
  tests/test_burst.py
  tests/test_entrypoints.py
Labels: minor

#38 Update release.yml
  .github/workflows/release.yml
Labels: CI/CD
