Repository ASFHyP3/hyp3-isce2, pull requests merged in 2024-07, with the labels that each got.

#221 Forgot to delete .flake8
  .flake8
Labels: bumpless

#216 Update time parsing in `merge-tops-bursts.py`
  CHANGELOG.md
  src/hyp3_isce2/merge_tops_bursts.py
  src/hyp3_isce2/water_mask.py
  tests/test_merge_tops_bursts.py
Labels: bug

#223 Release v1.1.2
  .flake8
  CHANGELOG.md
  src/hyp3_isce2/insar_stripmap.py
  src/hyp3_isce2/insar_tops.py
  src/hyp3_isce2/insar_tops_burst.py
  src/hyp3_isce2/logger.py
  src/hyp3_isce2/merge_tops_bursts.py
  src/hyp3_isce2/water_mask.py
  tests/test_merge_tops_bursts.py
Labels: patch

#226 Release v1.1.3
  .github/workflows/changelog.yml
  .github/workflows/create-jira-issue.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release-checklist-comment.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-version.yml
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  environment.yml
  pyproject.toml
Labels: patch
