Repository ASFHyP3/hyp3-isce2, pull requests merged in 2024-02, with the labels that each got.

#196 replace `os.system` with `subprocess.run`
  src/hyp3_isce2/water_mask.py
Labels: bumpless

#199 Release V1.0.0
  .gitignore
  CHANGELOG.md
  README.md
  images/coverage.svg
  pyproject.toml
  src/hyp3_isce2/__main__.py
  src/hyp3_isce2/burst.py
  src/hyp3_isce2/insar_tops.py
  src/hyp3_isce2/insar_tops_burst.py
  src/hyp3_isce2/merge_tops_bursts.py
  src/hyp3_isce2/metadata/templates/insar_burst/insar_burst_base.md.txt.j2
  src/hyp3_isce2/metadata/templates/insar_burst/insar_burst_merge_readme.md.txt.j2
  src/hyp3_isce2/metadata/templates/insar_burst/insar_burst_readme.md.txt.j2
  src/hyp3_isce2/metadata/templates/insar_burst/readme.md.txt.j2
  src/hyp3_isce2/utils.py
  src/hyp3_isce2/water_mask.py
  tests/conftest.py
  tests/data/create_merge_test_data.py
  tests/test_burst.py
  tests/test_merge_tops_bursts.py
  tests/test_utils.py
Labels: major

#202 Remove GSHHG reference
  src/hyp3_isce2/metadata/templates/insar_burst/insar_burst_base.md.txt.j2
Labels: bumpless

#203 Correct references to OpenStreetMap
  src/hyp3_isce2/metadata/templates/insar_burst/insar_burst_base.md.txt.j2
  src/hyp3_isce2/water_mask.py
Labels: bumpless

#204 Update changelog for water mask description updates
  CHANGELOG.md
Labels: patch

#205 Release v1.0.1
  .github/workflows/changelog.yml
  .github/workflows/create-jira-issue.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release-checklist-comment.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-version.yml
  .github/workflows/test-and-build.yml
  .trufflehog.txt
  CHANGELOG.md
  src/hyp3_isce2/metadata/templates/insar_burst/insar_burst_base.md.txt.j2
  src/hyp3_isce2/water_mask.py
Labels: patch
