Repository ASFHyP3/hyp3-isce2, pull requests merged in 2024-01, with the labels that each got.

#183 Release v0.9.3
  .github/workflows/changelog.yml
  .github/workflows/create-jira-issue.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release-checklist-comment.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-version.yml
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  environment.yml
  pyproject.toml
  src/hyp3_isce2/__init__.py
Labels: patch

#187 New Water Masks
  CHANGELOG.md
  pyproject.toml
  src/hyp3_isce2/insar_tops_burst.py
  src/hyp3_isce2/metadata/templates/insar_burst/readme.md.txt.j2
  src/hyp3_isce2/water_mask.py
  tests/data/water_mask_output_info.txt
  tests/test_water_mask.py
Labels: enhancement, minor

#193 README Update
  README.md
Labels: bumpless

#194 removed geopandas dep
  environment.yml
  pyproject.toml
Labels: bumpless

#192 Release 0.10.0
  CHANGELOG.md
  README.md
  environment.yml
  pyproject.toml
  src/hyp3_isce2/insar_tops_burst.py
  src/hyp3_isce2/metadata/templates/insar_burst/readme.md.txt.j2
  src/hyp3_isce2/water_mask.py
  tests/data/water_mask_output_info.txt
  tests/test_water_mask.py
Labels: minor
